publishDir = "ConfigManagement"
baseURL = "ConfigManagement/"
languageCode = "en-gb"
title = "Config-Management-Abstract"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

