publishDir = "../DockeringMinecraft"
baseURL = "https://seegras.github.io/DockeringMinecraft/"
languageCode = "en-gb"
title = "Dockering Minecraft"
theme = "reveal-hugo"
themesDir = "../themes"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

